language: php

php:
  - 5.5

sudo: false

cache:
  directories:
    - ~/.composer/cache

install:
  - export COMPOSER_ROOT_VERSION=1.1.x-dev
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 9a7f8f9aad55cad5a085b638f1059086ab20d76b591e08f7393c5bdb0299f0cc 

after_script:
  - ./bin/test-reporter
